### ISSUE TITLE
POST /client/{id}/source [ Register Source Data ] returns code 500 without details of the error  in response body

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/kernel-planckster#116]
![image](https://github.com/dream-aim-deliver/kernel-planckster/assets/5906242/285f675a-8ac6-4f62-8216-85f19182b1af)

**Comment by alebg** [comment]
@maany where do I fix this? I checked all the way down to the use case, all cases with code 500 return a message. Another problem I found, is that if MinIO is not running (running KP with just `poetry run dev`) then the view model returned has False status and it shows nicely the error message and so on, but the code of the response itself is 200. I've checked your old examples (demo feature) and I'm not really doing anything different.

**Comment by alebg** [comment]
These internal server errors are sometimes due to pydantic validations, for which we need to check kernel planckster's logs, and happen in endpoints other than this one too. Need to find a way to push them up with a proper helpful error message.
