### ISSUE TITLE
Add message type, trace, and thread

### ISSUE THREAD

**Issue by alebg** [dream-aim-deliver/kernel-planckster#131]
The message core and SQLAlchemy models need the following new attributes:

- message_type: enum["text", "image"]
- trace: string
- thread: to discuss and define how to handle

**Comment by ydamit** [comment]
Naming that we've decided on a structure with two tables: one table (based on the existing `message_base` table) that will be reoriented to message fragment as its grain, and another to contain a `thread_id`, with a common `message_id` key to link them. A thread can have one or more messages, and a message can have one or more message fragments.
